// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ImportBrainArmReducer from "../import_brain_arm_reducer";
import ImportBrainMetaReducer from "../import_brain_meta_reducer";
import RaidHitReducer from "../raid_hit_reducer";
import RaidJoinReducer from "../raid_join_reducer";
import RaidLeaveReducer from "../raid_leave_reducer";
import RaidStartReducer from "../raid_start_reducer";
import RaidUpdateReducer from "../raid_update_reducer";
import SetConsentReducer from "../set_consent_reducer";
import SubmitFightReducer from "../submit_fight_reducer";

export type ImportBrainArmParams = __Infer<typeof ImportBrainArmReducer>;
export type ImportBrainMetaParams = __Infer<typeof ImportBrainMetaReducer>;
export type RaidHitParams = __Infer<typeof RaidHitReducer>;
export type RaidJoinParams = __Infer<typeof RaidJoinReducer>;
export type RaidLeaveParams = __Infer<typeof RaidLeaveReducer>;
export type RaidStartParams = __Infer<typeof RaidStartReducer>;
export type RaidUpdateParams = __Infer<typeof RaidUpdateReducer>;
export type SetConsentParams = __Infer<typeof SetConsentReducer>;
export type SubmitFightParams = __Infer<typeof SubmitFightReducer>;

