// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  player: __t.identity(),
  at: __t.timestamp(),
  outcome: __t.string(),
  duration: __t.f64(),
  decisions: __t.u32(),
  dealt: __t.f64(),
  taken: __t.f64(),
  meanReward: __t.f64().name("mean_reward"),
  policyVersion: __t.u32().name("policy_version"),
  accepted: __t.bool(),
  reason: __t.string(),
});
