// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  arm: __t.u32(),
  a: __t.array(__t.f64()),
  b: __t.array(__t.f64()),
  ainv: __t.array(__t.f64()),
  theta: __t.array(__t.f64()),
  n: __t.u32(),
  rewardSum: __t.f64(),
};
