// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  raidId: __t.u64().name("raid_id"),
  owner: __t.string(),
  slot: __t.u32(),
  name: __t.string(),
  color: __t.string(),
  isBot: __t.bool().name("is_bot"),
  botStyle: __t.string().name("bot_style"),
  state: __t.string(),
  hits: __t.string(),
  skillsUsed: __t.u32().name("skills_used"),
  health: __t.f64(),
  armor: __t.f64(),
  dead: __t.bool(),
  dealt: __t.f64(),
});
