// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  endedAtMicros: __t.u64().name("ended_at_micros"),
  tick: __t.u32(),
  bossHp: __t.f64().name("boss_hp"),
  bossMaxHp: __t.f64().name("boss_max_hp"),
  policyVersion: __t.u32().name("policy_version"),
  sim: __t.string(),
  events: __t.string(),
});
