// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  policyVersion: __t.u32(),
  outcome: __t.string(),
  duration: __t.f64(),
  arms: __t.array(__t.u32()),
  contexts: __t.array(__t.f64()),
  rewards: __t.array(__t.f64()),
  dealt: __t.f64(),
  taken: __t.f64(),
};
